# This file was generated by GoReleaser. DO NOT EDIT.
class Diceroller < Formula
  desc "Deliver Go binaries as fast and easily as possible"
  homepage "https://derp.com"
  url "https://github.com/lukemilby/homebrew-diceroller/releases/download/v0.1.3/homebrew-diceroller_0.1.3_Darwin_x86_64.tar.gz"
  version "0.1.3"
  sha256 "64b5c72f6f339a0e2ab7fd09da1fa73ca7cc436230ec3fda29cc71750ae528ba"

  def install
    bin.install "homebrew-diceroller"
  end

  test do
    system "#{bin}/diceroller"
  end
end
