# This file was generated by GoReleaser. DO NOT EDIT.
class Diceroller < Formula
  desc "Deliver Go binaries as fast and easily as possible"
  homepage "https://derp.com"
  url "https://github.com/lukemilby/homebrew-diceroller/releases/download/v0.1.3/homebrew-diceroller_0.1.3_Darwin_x86_64.tar.gz"
  version "0.1.3"
  sha256 "daa358c91b22b846a56eefde9af5567e5e7a51307b6061cdd9b9d1b0c7997132"

  def install
    bin.install "diceroller"
  end

  test do
    system "#{bin}/diceroller"
  end
end
